### ISSUE TITLE
代码和部分pg版本不兼容

### ISSUE THREAD

**Issue by ketra21** [geocompass/pg-tyshxydm#1]
pg-validate-tyshxydm.sql
1、在PostgreSQL 8.3.23版本中运行，`tyshxydm := substr(tyshxydm,9,9);`处报错，原因是低版本pg不允许对入参进行赋值，解决办法是增加一个中转变量；

2、`select tyshxydm ~ '^[0-9A-Z]+$'  into is_correct;`修改为了：
`select tyshxydm ~ '^[0-9A-Z]+$' AND tyshxydm !~ '[IOZSV]' into is_correct;`

**Comment by MrSmallLiu** [comment]
感谢您的指正

**Comment by MrSmallLiu** [comment]
对于您的问题给您回复。

**Comment by MrSmallLiu** [comment]
1.暂时不支持低版本了

**Comment by MrSmallLiu** [comment]
2.原组织机构代码中是可以包含 IOZSV的，所以在最初始进行判断是不对的
