### ISSUE TITLE
代码逻辑修正

### ISSUE THREAD

**Issue by ketra21** [geocompass/pg-tyshxydm#2]
在pg-validate-tyshxydm.sql中，当jymCode =10，且substr(tyshxydm,9, 1) != "X"时，没有输出。
`		 if jymCode =10 then 
			 if (length(tyshxydm) =9 and  substr(tyshxydm,9, 1) = "X") then
				is_correct := true;
				return  is_correct;
				end if ;
			end if ;`应修改为
`		 if jymCode =10 then 
			 if (length(tyshxydm) =9 and  substr(tyshxydm,9, 1) = "X") then
				is_correct := true;
				return  is_correct;
                             else
				is_correct := false;
				return  is_correct;
				end if ;
			end if ;`

**Comment by MrSmallLiu** [comment]
感谢您的指正

**Comment by MrSmallLiu** [comment]
感谢您的指正，已经修改提交
